Traceback (most recent call last):
  File "/home/janulm/janulm_agent_nodes/agent-net/planetoid_cora.py", line 198, in <module>
    print("max result test acc: ",results[np.argmax(results)],np.argmax(results))
IndexError: index 2334 is out of bounds for axis 0 with size 3
